#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertLogindetail(Logindetail instance);
  partial void UpdateLogindetail(Logindetail instance);
  partial void DeleteLogindetail(Logindetail instance);
  partial void InsertRegistration(Registration instance);
  partial void UpdateRegistration(Registration instance);
  partial void DeleteRegistration(Registration instance);
  partial void InsertEvent(Event instance);
  partial void UpdateEvent(Event instance);
  partial void DeleteEvent(Event instance);
  partial void InsertFeedback(Feedback instance);
  partial void UpdateFeedback(Feedback instance);
  partial void DeleteFeedback(Feedback instance);
  partial void InsertGardner_Reg(Gardner_Reg instance);
  partial void UpdateGardner_Reg(Gardner_Reg instance);
  partial void DeleteGardner_Reg(Gardner_Reg instance);
  partial void InsertMsg_Detail(Msg_Detail instance);
  partial void UpdateMsg_Detail(Msg_Detail instance);
  partial void DeleteMsg_Detail(Msg_Detail instance);
  partial void InsertProduct(Product instance);
  partial void UpdateProduct(Product instance);
  partial void DeleteProduct(Product instance);
  partial void InsertVendor_reg(Vendor_reg instance);
  partial void UpdateVendor_reg(Vendor_reg instance);
  partial void DeleteVendor_reg(Vendor_reg instance);
  partial void InsertCompose(Compose instance);
  partial void UpdateCompose(Compose instance);
  partial void DeleteCompose(Compose instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Logindetail> Logindetails
	{
		get
		{
			return this.GetTable<Logindetail>();
		}
	}
	
	public System.Data.Linq.Table<Registration> Registrations
	{
		get
		{
			return this.GetTable<Registration>();
		}
	}
	
	public System.Data.Linq.Table<Event> Events
	{
		get
		{
			return this.GetTable<Event>();
		}
	}
	
	public System.Data.Linq.Table<Feedback> Feedbacks
	{
		get
		{
			return this.GetTable<Feedback>();
		}
	}
	
	public System.Data.Linq.Table<Gardner_Reg> Gardner_Regs
	{
		get
		{
			return this.GetTable<Gardner_Reg>();
		}
	}
	
	public System.Data.Linq.Table<Msg_Detail> Msg_Details
	{
		get
		{
			return this.GetTable<Msg_Detail>();
		}
	}
	
	public System.Data.Linq.Table<Product> Products
	{
		get
		{
			return this.GetTable<Product>();
		}
	}
	
	public System.Data.Linq.Table<Vendor_reg> Vendor_regs
	{
		get
		{
			return this.GetTable<Vendor_reg>();
		}
	}
	
	public System.Data.Linq.Table<Compose> Composes
	{
		get
		{
			return this.GetTable<Compose>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Logindetails")]
public partial class Logindetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _user_id;
	
	private string _password;
	
	private string _utype;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnutypeChanging(string value);
    partial void OnutypeChanged();
    #endregion
	
	public Logindetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_utype", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string utype
	{
		get
		{
			return this._utype;
		}
		set
		{
			if ((this._utype != value))
			{
				this.OnutypeChanging(value);
				this.SendPropertyChanging();
				this._utype = value;
				this.SendPropertyChanged("utype");
				this.OnutypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registration")]
public partial class Registration : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _user_id;
	
	private string _name;
	
	private string _age;
	
	private string _email;
	
	private string _address;
	
	private string _gender;
	
	private string _contactno;
	
	private string _password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnageChanging(string value);
    partial void OnageChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OncontactnoChanging(string value);
    partial void OncontactnoChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public Registration()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="VarChar(50)")]
	public string age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactno", DbType="VarChar(50)")]
	public string contactno
	{
		get
		{
			return this._contactno;
		}
		set
		{
			if ((this._contactno != value))
			{
				this.OncontactnoChanging(value);
				this.SendPropertyChanging();
				this._contactno = value;
				this.SendPropertyChanged("contactno");
				this.OncontactnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Events")]
public partial class Event : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _EventId;
	
	private string _EventName;
	
	private string _Organizer;
	
	private string _Venue;
	
	private string _Date;
	
	private string _Time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnEventNameChanging(string value);
    partial void OnEventNameChanged();
    partial void OnOrganizerChanging(string value);
    partial void OnOrganizerChanged();
    partial void OnVenueChanging(string value);
    partial void OnVenueChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    #endregion
	
	public Event()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int EventId
	{
		get
		{
			return this._EventId;
		}
		set
		{
			if ((this._EventId != value))
			{
				this.OnEventIdChanging(value);
				this.SendPropertyChanging();
				this._EventId = value;
				this.SendPropertyChanged("EventId");
				this.OnEventIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventName", DbType="VarChar(MAX)")]
	public string EventName
	{
		get
		{
			return this._EventName;
		}
		set
		{
			if ((this._EventName != value))
			{
				this.OnEventNameChanging(value);
				this.SendPropertyChanging();
				this._EventName = value;
				this.SendPropertyChanged("EventName");
				this.OnEventNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organizer", DbType="VarChar(MAX)")]
	public string Organizer
	{
		get
		{
			return this._Organizer;
		}
		set
		{
			if ((this._Organizer != value))
			{
				this.OnOrganizerChanging(value);
				this.SendPropertyChanging();
				this._Organizer = value;
				this.SendPropertyChanged("Organizer");
				this.OnOrganizerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Venue", DbType="VarChar(MAX)")]
	public string Venue
	{
		get
		{
			return this._Venue;
		}
		set
		{
			if ((this._Venue != value))
			{
				this.OnVenueChanging(value);
				this.SendPropertyChanging();
				this._Venue = value;
				this.SendPropertyChanged("Venue");
				this.OnVenueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="VarChar(MAX)")]
	public string Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="VarChar(MAX)")]
	public string Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Feedback")]
public partial class Feedback : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _FId;
	
	private string _Name;
	
	private string _Email;
	
	private string _Message;
	
	private string _Date;
	
	private string _Time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFIdChanging(int value);
    partial void OnFIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    #endregion
	
	public Feedback()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int FId
	{
		get
		{
			return this._FId;
		}
		set
		{
			if ((this._FId != value))
			{
				this.OnFIdChanging(value);
				this.SendPropertyChanging();
				this._FId = value;
				this.SendPropertyChanged("FId");
				this.OnFIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX)")]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="VarChar(MAX)")]
	public string Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="VarChar(MAX)")]
	public string Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gardner_Reg")]
public partial class Gardner_Reg : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _GardnerId;
	
	private string _GardnerName;
	
	private string _ContactNo;
	
	private string _IdProof;
	
	private string _Address;
	
	private string _PreferredLocation;
	
	private string _GardeningExperience;
	
	private string _JobType;
	
	private string _PaymentAmount;
	
	private string _Date;
	
	private string _Time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGardnerIdChanging(int value);
    partial void OnGardnerIdChanged();
    partial void OnGardnerNameChanging(string value);
    partial void OnGardnerNameChanged();
    partial void OnContactNoChanging(string value);
    partial void OnContactNoChanged();
    partial void OnIdProofChanging(string value);
    partial void OnIdProofChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPreferredLocationChanging(string value);
    partial void OnPreferredLocationChanged();
    partial void OnGardeningExperienceChanging(string value);
    partial void OnGardeningExperienceChanged();
    partial void OnJobTypeChanging(string value);
    partial void OnJobTypeChanged();
    partial void OnPaymentAmountChanging(string value);
    partial void OnPaymentAmountChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    #endregion
	
	public Gardner_Reg()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GardnerId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int GardnerId
	{
		get
		{
			return this._GardnerId;
		}
		set
		{
			if ((this._GardnerId != value))
			{
				this.OnGardnerIdChanging(value);
				this.SendPropertyChanging();
				this._GardnerId = value;
				this.SendPropertyChanged("GardnerId");
				this.OnGardnerIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GardnerName", DbType="VarChar(MAX)")]
	public string GardnerName
	{
		get
		{
			return this._GardnerName;
		}
		set
		{
			if ((this._GardnerName != value))
			{
				this.OnGardnerNameChanging(value);
				this.SendPropertyChanging();
				this._GardnerName = value;
				this.SendPropertyChanged("GardnerName");
				this.OnGardnerNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="VarChar(MAX)")]
	public string ContactNo
	{
		get
		{
			return this._ContactNo;
		}
		set
		{
			if ((this._ContactNo != value))
			{
				this.OnContactNoChanging(value);
				this.SendPropertyChanging();
				this._ContactNo = value;
				this.SendPropertyChanged("ContactNo");
				this.OnContactNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProof", DbType="VarChar(MAX)")]
	public string IdProof
	{
		get
		{
			return this._IdProof;
		}
		set
		{
			if ((this._IdProof != value))
			{
				this.OnIdProofChanging(value);
				this.SendPropertyChanging();
				this._IdProof = value;
				this.SendPropertyChanged("IdProof");
				this.OnIdProofChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredLocation", DbType="VarChar(MAX)")]
	public string PreferredLocation
	{
		get
		{
			return this._PreferredLocation;
		}
		set
		{
			if ((this._PreferredLocation != value))
			{
				this.OnPreferredLocationChanging(value);
				this.SendPropertyChanging();
				this._PreferredLocation = value;
				this.SendPropertyChanged("PreferredLocation");
				this.OnPreferredLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GardeningExperience", DbType="VarChar(MAX)")]
	public string GardeningExperience
	{
		get
		{
			return this._GardeningExperience;
		}
		set
		{
			if ((this._GardeningExperience != value))
			{
				this.OnGardeningExperienceChanging(value);
				this.SendPropertyChanging();
				this._GardeningExperience = value;
				this.SendPropertyChanged("GardeningExperience");
				this.OnGardeningExperienceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobType", DbType="VarChar(MAX)")]
	public string JobType
	{
		get
		{
			return this._JobType;
		}
		set
		{
			if ((this._JobType != value))
			{
				this.OnJobTypeChanging(value);
				this.SendPropertyChanging();
				this._JobType = value;
				this.SendPropertyChanged("JobType");
				this.OnJobTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentAmount", DbType="VarChar(MAX)")]
	public string PaymentAmount
	{
		get
		{
			return this._PaymentAmount;
		}
		set
		{
			if ((this._PaymentAmount != value))
			{
				this.OnPaymentAmountChanging(value);
				this.SendPropertyChanging();
				this._PaymentAmount = value;
				this.SendPropertyChanged("PaymentAmount");
				this.OnPaymentAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="VarChar(MAX)")]
	public string Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="VarChar(MAX)")]
	public string Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Msg_Detail")]
public partial class Msg_Detail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MsgId;
	
	private string _To;
	
	private string _Subject;
	
	private string _Message;
	
	private string _Status;
	
	private string _Date;
	
	private string _Time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMsgIdChanging(int value);
    partial void OnMsgIdChanged();
    partial void OnToChanging(string value);
    partial void OnToChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    #endregion
	
	public Msg_Detail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int MsgId
	{
		get
		{
			return this._MsgId;
		}
		set
		{
			if ((this._MsgId != value))
			{
				this.OnMsgIdChanging(value);
				this.SendPropertyChanging();
				this._MsgId = value;
				this.SendPropertyChanged("MsgId");
				this.OnMsgIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[To]", Storage="_To", DbType="VarChar(MAX)")]
	public string To
	{
		get
		{
			return this._To;
		}
		set
		{
			if ((this._To != value))
			{
				this.OnToChanging(value);
				this.SendPropertyChanging();
				this._To = value;
				this.SendPropertyChanged("To");
				this.OnToChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="VarChar(MAX)")]
	public string Subject
	{
		get
		{
			return this._Subject;
		}
		set
		{
			if ((this._Subject != value))
			{
				this.OnSubjectChanging(value);
				this.SendPropertyChanging();
				this._Subject = value;
				this.SendPropertyChanged("Subject");
				this.OnSubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX)")]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(MAX)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="VarChar(MAX)")]
	public string Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="VarChar(MAX)")]
	public string Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ProductId;
	
	private string _ProductName;
	
	private string _ProductImg;
	
	private string _ProductDesc;
	
	private string _ProductType;
	
	private string _OriginalPrice;
	
	private string _Price;
	
	private string _Discount;
	
	private string _VendorName;
	
	private string _Address;
	
	private string _Contact;
	
	private string _Date;
	
	private string _Time;
	
	private string _Link;
	
	private string _Rating;
	
	private string _Feedback;
	
	private string _UserId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnProductImgChanging(string value);
    partial void OnProductImgChanged();
    partial void OnProductDescChanging(string value);
    partial void OnProductDescChanged();
    partial void OnProductTypeChanging(string value);
    partial void OnProductTypeChanged();
    partial void OnOriginalPriceChanging(string value);
    partial void OnOriginalPriceChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void OnDiscountChanging(string value);
    partial void OnDiscountChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnRatingChanging(string value);
    partial void OnRatingChanged();
    partial void OnFeedbackChanging(string value);
    partial void OnFeedbackChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    #endregion
	
	public Product()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ProductId
	{
		get
		{
			return this._ProductId;
		}
		set
		{
			if ((this._ProductId != value))
			{
				this.OnProductIdChanging(value);
				this.SendPropertyChanging();
				this._ProductId = value;
				this.SendPropertyChanged("ProductId");
				this.OnProductIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(MAX)")]
	public string ProductName
	{
		get
		{
			return this._ProductName;
		}
		set
		{
			if ((this._ProductName != value))
			{
				this.OnProductNameChanging(value);
				this.SendPropertyChanging();
				this._ProductName = value;
				this.SendPropertyChanged("ProductName");
				this.OnProductNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductImg", DbType="VarChar(MAX)")]
	public string ProductImg
	{
		get
		{
			return this._ProductImg;
		}
		set
		{
			if ((this._ProductImg != value))
			{
				this.OnProductImgChanging(value);
				this.SendPropertyChanging();
				this._ProductImg = value;
				this.SendPropertyChanged("ProductImg");
				this.OnProductImgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDesc", DbType="VarChar(MAX)")]
	public string ProductDesc
	{
		get
		{
			return this._ProductDesc;
		}
		set
		{
			if ((this._ProductDesc != value))
			{
				this.OnProductDescChanging(value);
				this.SendPropertyChanging();
				this._ProductDesc = value;
				this.SendPropertyChanged("ProductDesc");
				this.OnProductDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductType", DbType="VarChar(MAX)")]
	public string ProductType
	{
		get
		{
			return this._ProductType;
		}
		set
		{
			if ((this._ProductType != value))
			{
				this.OnProductTypeChanging(value);
				this.SendPropertyChanging();
				this._ProductType = value;
				this.SendPropertyChanged("ProductType");
				this.OnProductTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalPrice", DbType="VarChar(MAX)")]
	public string OriginalPrice
	{
		get
		{
			return this._OriginalPrice;
		}
		set
		{
			if ((this._OriginalPrice != value))
			{
				this.OnOriginalPriceChanging(value);
				this.SendPropertyChanging();
				this._OriginalPrice = value;
				this.SendPropertyChanged("OriginalPrice");
				this.OnOriginalPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="VarChar(MAX)")]
	public string Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="VarChar(MAX)")]
	public string Discount
	{
		get
		{
			return this._Discount;
		}
		set
		{
			if ((this._Discount != value))
			{
				this.OnDiscountChanging(value);
				this.SendPropertyChanging();
				this._Discount = value;
				this.SendPropertyChanged("Discount");
				this.OnDiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="VarChar(MAX)")]
	public string VendorName
	{
		get
		{
			return this._VendorName;
		}
		set
		{
			if ((this._VendorName != value))
			{
				this.OnVendorNameChanging(value);
				this.SendPropertyChanging();
				this._VendorName = value;
				this.SendPropertyChanged("VendorName");
				this.OnVendorNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(MAX)")]
	public string Contact
	{
		get
		{
			return this._Contact;
		}
		set
		{
			if ((this._Contact != value))
			{
				this.OnContactChanging(value);
				this.SendPropertyChanging();
				this._Contact = value;
				this.SendPropertyChanged("Contact");
				this.OnContactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="VarChar(MAX)")]
	public string Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="VarChar(MAX)")]
	public string Time
	{
		get
		{
			return this._Time;
		}
		set
		{
			if ((this._Time != value))
			{
				this.OnTimeChanging(value);
				this.SendPropertyChanging();
				this._Time = value;
				this.SendPropertyChanged("Time");
				this.OnTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(MAX)")]
	public string Link
	{
		get
		{
			return this._Link;
		}
		set
		{
			if ((this._Link != value))
			{
				this.OnLinkChanging(value);
				this.SendPropertyChanging();
				this._Link = value;
				this.SendPropertyChanged("Link");
				this.OnLinkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="VarChar(MAX)")]
	public string Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this.OnRatingChanging(value);
				this.SendPropertyChanging();
				this._Rating = value;
				this.SendPropertyChanged("Rating");
				this.OnRatingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feedback", DbType="VarChar(MAX)")]
	public string Feedback
	{
		get
		{
			return this._Feedback;
		}
		set
		{
			if ((this._Feedback != value))
			{
				this.OnFeedbackChanging(value);
				this.SendPropertyChanging();
				this._Feedback = value;
				this.SendPropertyChanged("Feedback");
				this.OnFeedbackChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(MAX)")]
	public string UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vendor_reg")]
public partial class Vendor_reg : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _VId;
	
	private string _ShopRegName;
	
	private string _ContactNo;
	
	private string _ContactEmail;
	
	private string _Address;
	
	private string _Pincode;
	
	private string _ShopIdProof;
	
	private string _ProductDetail;
	
	private string _Email;
	
	private string _Password;
	
	private string _secques;
	
	private string _secans;
	
	private string _VendorName;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVIdChanging(int value);
    partial void OnVIdChanged();
    partial void OnShopRegNameChanging(string value);
    partial void OnShopRegNameChanged();
    partial void OnContactNoChanging(string value);
    partial void OnContactNoChanged();
    partial void OnContactEmailChanging(string value);
    partial void OnContactEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPincodeChanging(string value);
    partial void OnPincodeChanged();
    partial void OnShopIdProofChanging(string value);
    partial void OnShopIdProofChanged();
    partial void OnProductDetailChanging(string value);
    partial void OnProductDetailChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnsecquesChanging(string value);
    partial void OnsecquesChanged();
    partial void OnsecansChanging(string value);
    partial void OnsecansChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    #endregion
	
	public Vendor_reg()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int VId
	{
		get
		{
			return this._VId;
		}
		set
		{
			if ((this._VId != value))
			{
				this.OnVIdChanging(value);
				this.SendPropertyChanging();
				this._VId = value;
				this.SendPropertyChanged("VId");
				this.OnVIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopRegName", DbType="VarChar(MAX)")]
	public string ShopRegName
	{
		get
		{
			return this._ShopRegName;
		}
		set
		{
			if ((this._ShopRegName != value))
			{
				this.OnShopRegNameChanging(value);
				this.SendPropertyChanging();
				this._ShopRegName = value;
				this.SendPropertyChanged("ShopRegName");
				this.OnShopRegNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="VarChar(MAX)")]
	public string ContactNo
	{
		get
		{
			return this._ContactNo;
		}
		set
		{
			if ((this._ContactNo != value))
			{
				this.OnContactNoChanging(value);
				this.SendPropertyChanging();
				this._ContactNo = value;
				this.SendPropertyChanged("ContactNo");
				this.OnContactNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="VarChar(MAX)")]
	public string ContactEmail
	{
		get
		{
			return this._ContactEmail;
		}
		set
		{
			if ((this._ContactEmail != value))
			{
				this.OnContactEmailChanging(value);
				this.SendPropertyChanging();
				this._ContactEmail = value;
				this.SendPropertyChanged("ContactEmail");
				this.OnContactEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pincode", DbType="VarChar(MAX)")]
	public string Pincode
	{
		get
		{
			return this._Pincode;
		}
		set
		{
			if ((this._Pincode != value))
			{
				this.OnPincodeChanging(value);
				this.SendPropertyChanging();
				this._Pincode = value;
				this.SendPropertyChanged("Pincode");
				this.OnPincodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopIdProof", DbType="VarChar(MAX)")]
	public string ShopIdProof
	{
		get
		{
			return this._ShopIdProof;
		}
		set
		{
			if ((this._ShopIdProof != value))
			{
				this.OnShopIdProofChanging(value);
				this.SendPropertyChanging();
				this._ShopIdProof = value;
				this.SendPropertyChanged("ShopIdProof");
				this.OnShopIdProofChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDetail", DbType="VarChar(MAX)")]
	public string ProductDetail
	{
		get
		{
			return this._ProductDetail;
		}
		set
		{
			if ((this._ProductDetail != value))
			{
				this.OnProductDetailChanging(value);
				this.SendPropertyChanging();
				this._ProductDetail = value;
				this.SendPropertyChanged("ProductDetail");
				this.OnProductDetailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(MAX)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secques", DbType="VarChar(MAX)")]
	public string secques
	{
		get
		{
			return this._secques;
		}
		set
		{
			if ((this._secques != value))
			{
				this.OnsecquesChanging(value);
				this.SendPropertyChanging();
				this._secques = value;
				this.SendPropertyChanged("secques");
				this.OnsecquesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secans", DbType="VarChar(MAX)")]
	public string secans
	{
		get
		{
			return this._secans;
		}
		set
		{
			if ((this._secans != value))
			{
				this.OnsecansChanging(value);
				this.SendPropertyChanging();
				this._secans = value;
				this.SendPropertyChanged("secans");
				this.OnsecansChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="VarChar(MAX)")]
	public string VendorName
	{
		get
		{
			return this._VendorName;
		}
		set
		{
			if ((this._VendorName != value))
			{
				this.OnVendorNameChanging(value);
				this.SendPropertyChanging();
				this._VendorName = value;
				this.SendPropertyChanged("VendorName");
				this.OnVendorNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Compose")]
public partial class Compose : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _composeId;
	
	private string _to;
	
	private string _from;
	
	private string _msg;
	
	private string _subject;
	
	private string _date;
	
	private string _time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncomposeIdChanging(int value);
    partial void OncomposeIdChanged();
    partial void OntoChanging(string value);
    partial void OntoChanged();
    partial void OnfromChanging(string value);
    partial void OnfromChanged();
    partial void OnmsgChanging(string value);
    partial void OnmsgChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    #endregion
	
	public Compose()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_composeId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int composeId
	{
		get
		{
			return this._composeId;
		}
		set
		{
			if ((this._composeId != value))
			{
				this.OncomposeIdChanging(value);
				this.SendPropertyChanging();
				this._composeId = value;
				this.SendPropertyChanged("composeId");
				this.OncomposeIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[to]", Storage="_to", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string to
	{
		get
		{
			return this._to;
		}
		set
		{
			if ((this._to != value))
			{
				this.OntoChanging(value);
				this.SendPropertyChanging();
				this._to = value;
				this.SendPropertyChanged("to");
				this.OntoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[from]", Storage="_from", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string from
	{
		get
		{
			return this._from;
		}
		set
		{
			if ((this._from != value))
			{
				this.OnfromChanging(value);
				this.SendPropertyChanging();
				this._from = value;
				this.SendPropertyChanged("from");
				this.OnfromChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string msg
	{
		get
		{
			return this._msg;
		}
		set
		{
			if ((this._msg != value))
			{
				this.OnmsgChanging(value);
				this.SendPropertyChanging();
				this._msg = value;
				this.SendPropertyChanged("msg");
				this.OnmsgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string subject
	{
		get
		{
			return this._subject;
		}
		set
		{
			if ((this._subject != value))
			{
				this.OnsubjectChanging(value);
				this.SendPropertyChanging();
				this._subject = value;
				this.SendPropertyChanged("subject");
				this.OnsubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this.OntimeChanging(value);
				this.SendPropertyChanging();
				this._time = value;
				this.SendPropertyChanged("time");
				this.OntimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
